version: '2'
services:
    elastic-app:
        image: elastic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://elastic-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=elastic
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    elastic-mongodb:
        extends:
            file: mongodb.yml
            service: elastic-mongodb
